proyecto_front:
    resource: "@ProyectoFrontBundle/Resources/config/routing.yml"
    prefix:   /

proyecto_principal:
    resource: "@ProyectoPrincipalBundle/Resources/config/routing.yml"
    prefix:   /control

